# This file contains the default configuration for the market maker simulation.

# Market Configuration
market:
  tick_size: 0.01
  lot_size: 100
  initial_price: 100.0
  max_order_book_depth: 10


# Market Maker Configuration
market_maker:
  trader_id: "MM_01"
  initial_capital: 1000000.0
  base_spread: 0.18
  quote_size: 1000
  max_inventory: 10000
  inventory_skew_factor: 0.0001
  max_orders_per_side: 3
  num_quote_levels: 3
  level_spacing_ticks: 2 # Number of ticks between levels


# Risk Management
risk:
  max_position_value: 500000.0
  stop_loss_threshold: -10000.0
  inventory_pct_limit: 0.8 # Start reducing when at x% of max inventory

# Model Configuration
models:
  garch:
    p: 1 # GARCH lag order
    q: 1 # ARCH lag order
    vol_target: 0.15 # Annual volatility target
    update_frequency: 100 # Refit every N ticks
    min_observations: 50 # Minimum observations for fitting
    use_egarch: True # Use EGARCH model


  microprice:
    use_multi_level: True
    depth_levels: 5
    depth_decay: 0.5 # Use exponential decay for deeper levels

  
  adverse_selection:
    lookback_trades: 20
    toxicity_threshold: 0.6
    decay_factor: 0.95
    min_trades_for_scoring: 5


# Strategy Parameters
strategy:
  spread_components:
    base_weight: 0.2
    volatility_weight: 0.3
    inventory_weight: 0.2
    adverse_weight: 0.2
    imbalance_weight: 0.1

  quote_sizing:
    defensive_mode_threshold: 5 # Recent sweeps before defensive
    sweep_detection_levels: 2
    size_reduction_per_level: 0.8


# Market dynamics
market_dynamics:
  volatility: 0.002
  mean_reversion_speed: 0.01
  event_probability: 0.02


# Participant Configuration
participants:
  informed_traders:
    count: 2
    probability: 0.3
    accuracy: 0.7

  
  noise_traders:
    count: 10
    probability: 0.5
    price_sensitivity: 0.002

  
  arbitrageurs:
    count: 1
    threshold: 0.001

  
  momentum_traders:
    count: 1
    lookback_period: 10
    momentum_threshold: 0.0005


# Simulation Parameters
simulation:
  ticks: 10000
  random_seed: 37
  tick_frequency_ms: 100
  warmup_period: 100


# Fees
fees:
  exchange_fee: 0.00001
  latency_cost: 0.0001